let express=require("express")
let mongoose=require("mongoose")
const rt = require("./routes/rt")
mongoose.connect("mongodb://127.0.0.1:27017/V24HFS1").then(()=>{
    console.log("k")
})
let app=express()
app.use(express.json())
app.use("/",rt)
app.listen(5000)